### ISSUE TITLE
$SCITECOPATH is wrong on Apple Silicon processors

### ISSUE THREAD

**Issue by dertuxmalwieder** [rhaberkorn/sciteco#13]
Using the sample_teco.ini file, I found that it *seems* to use the wrong paths:

```
% pwd
/Users/tux0r/git/sciteco/src
% ./sciteco  # using the self-compiled version
Info: Added new unnamed file to ring.
Error: Datei »/usr/local/share/sciteco/lib/color.tes« konnte nicht geöffnet werden: No such file or directory
```

I actually wonder why it defaults to `/usr/local`. That also happens after `make install` and using the "installed" version.

**Comment by rhaberkorn** [comment]
Could I see your config.log please? The GNU build system (Autoconf) defaults to `/usr/local/` unless you specify `--prefix`. The default SCITECOPATH should be relative to `--datadir`. Quite possibly you changed the `--prefix`, ran `make` but Autoconf did not notice it has to rebuild everything, so `/usr/local` was still in the old compiled objects. In this case, a `make clean all`, followed by `make install` should fix things.

**Comment by rhaberkorn** [comment]
btw. you can also

    export SCITECOPATH=/usr/share/sciteco/lib

as a workaround

**Comment by dertuxmalwieder** [comment]
I have not modified the prefix on this machine.

```
% make clean all
% sudo make install
% cd src
% ./sciteco
Info: Added new unnamed file to ring.
Error: Datei »/usr/local/share/sciteco/lib/color.tes« konnte nicht geöffnet werden: No such file or directory
```

[config.log](https://github.com/rhaberkorn/sciteco/files/11253140/config.log)

**Comment by rhaberkorn** [comment]
If you have not modified the prefix, that means SciTECO got installed into `/usr/local`. Then why weren't the macros in `/usr/local/share/sciteco/lib` to begin with?

**Comment by dertuxmalwieder** [comment]
That's a pretty good question which I sadly can't answer.
