### ISSUE TITLE
EB uses wrong directory

### ISSUE THREAD

**Issue by blakemcbride** [rhaberkorn/sciteco#14]
I am doing:

cd ~/tmp
sciteco
EBt.txt$$

Instead of opening the t.txt file in the ~/tmp directory, it is looking for the file in the /home/blake/Backup/sciteco directory which is where I built sciteco.  Seem like it should be using my current directoty instead of where sciteco was built.

Thanks!

**Comment by rhaberkorn** [comment]
Hello Blake!
I guess you just downloaded and built from the tarball?
What you observe is actually not considered a bug. It's the session.tes module, which is enabled by default in `~/.teco_ini` (if you just copied it from `sample.teco_ini`). It will save your editor state (buffers and current directory) in `~/.teco_session`. If you just invoke `sciteco` without arguments, the previous global session will be restored. It is also possible to enable per-repository sessions by uncommenting `M[session.vcs]` in `~/.teco_ini`. If you run `sciteco t.txt`, you will find that the current working directory is not changed.

Anyway, you can always change the current working directory using the `FG...$` (Folder Go - I  ran out of mnemonics) command.

It is also possible to disable restoring the working directory by setting `0U[session.savedir]` after `EM^EQ[$SCITECOPATH]/session.tes$` in `~/.teco_ini`. Or you can completely disable the "session" feature by commenting out the mung of `session.tes`.

**Comment by blakemcbride** [comment]
Having a previously saved session state and keeping it in a known place is good.  I think the session should save what files were being edited and perhaps other information about the state of those files.  However, I do not think it should save the current working directory!  That is highly unexpected behavior.

So, when sciteco is started without arguments, loading the previous files is good.  But the current working directory should remain IMO.  Otherwise:

1. You know what directory you were in when you started sciteco
2. you create a new file
3. SUPPRISE!  The newly created file gets put in some directory you were in yesterday!!!

**Comment by rhaberkorn** [comment]
Well, you can as I wrote already disable the current-working-dir restoration if you don't like it. I actually do like and use it.

If you by accident created a file in the wrong directory, you can always quickly undo that by rubbing out the previous command with Ctrl+W. Or just save the file under a new name using `EWnew-name$` instead of `EW$` (the latter would use the name established by EB). New files are not written until the first EW, so in any case you don't leave any stray files around.

**Comment by blakemcbride** [comment]
That'll work.  Thanks!
