### ISSUE TITLE
Build problem - not detecting glib correctly

### ISSUE THREAD

**Issue by blakemcbride** [rhaberkorn/sciteco#21]
Configure is saying I need glib-2 version >= 2.44, however, (as far as I can tell) I have version 2.80 installed.  Not sure what to do.
I am using Fedora 40 on a modern and large system.

```
$ ./configure
[...]
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for glib-2.0 >= 2.44... no
configure: error: Package requirements (glib-2.0 >= 2.44) were not met:

Package 'glib-2.0', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables LIBGLIB_CFLAGS
and LIBGLIB_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
$ ls -l /lib64/libglib-*
lrwxrwxrwx. 1 root root      23 Jun 17 19:00 /lib64/libglib-2.0.so.0 -> libglib-2.0.so.0.8000.3
-rwxr-xr-x. 1 root root 1383688 Jun 17 19:00 /lib64/libglib-2.0.so.0.8000.3
$ uname -r
6.10.10-200.fc40.x86_64
$
```

**Comment by rhaberkorn** [comment]
Hello Blake! Have you got the [glib2-devel](https://packages.fedoraproject.org/pkgs/glib2/glib2-devel/fedora-40-updates.html) package installed? It _should_ contain the glib-2.0.pc pkgconfig file that Autoconf is looking for.

What's printed by

    pkg-config --modversion glib-2.0

You can also attach the file config.log. That might be useful.

**Comment by blakemcbride** [comment]
Installing glib2-devel worked.  Thanks!  sciteco looks great!  Thanks!
