### ISSUE TITLE
No more binary builds?

### ISSUE THREAD

**Issue by dertuxmalwieder** [rhaberkorn/sciteco#30]
From the 2.2.0 announcement:

> Curses builds for Windows (sciteco-pdcurses_2.2.0_win32.zip) are based on [PDCursesMod](https://github.com/Bill-Gray/PDCursesMod).

Great! Where are they?

**Comment by rhaberkorn** [comment]
My countless users immediately notice missing files. ;-)

I made the release mainly, so I can update the FreeBSD package, which is about to be merged into FreeBSD ports. I didn't want to let them wait and wanted to add the rest of the binaries afterwards. But I will see to it today.

**Comment by dertuxmalwieder** [comment]
Well, I wanted to update the Chocolatey port... ;-)

**Comment by rhaberkorn** [comment]
Uploaded. Have fun.

**Comment by rhaberkorn** [comment]
It's by the way interesting that the majority of downloads on Github are from the PDCurses Win32 version, supposedly via Chocolatey (if you are referencing the Github releases).
Being in package repositories obviously helps to stand out against the noise.

**Comment by dertuxmalwieder** [comment]
Version 2.2.0 has 6 downloads according to the package overview, but I assume that some automatisms are in place.

**Comment by rhaberkorn** [comment]
> Version 2.2.0 has 6 downloads according to the package overview, but I assume that some automatisms are in place.

No, that's pretty much everything. See https://githubstats0.firebaseapp.com/
There aren't many downloads at all. But of the few downloads, Windows certainly rules (unfortunately). Sourceforge statistics are similar (there's even less traffic). The Ubuntu PPA is not used by anybody.

**Comment by dertuxmalwieder** [comment]
I imagine that most non-Windows users just do the Makefile dance. And the FreeBSD troupe is just small on the desktop, for no good reason whatsoever.

Ubuntu people probably don't know TECO. ;-)

**Comment by rhaberkorn** [comment]
> And the FreeBSD troupe is just small on the desktop, for no good reason whatsoever.

Runs excellent. On my almost 8 year old Thinkpad at least...

**Comment by dertuxmalwieder** [comment]
Sure does (although I have moved on to OpenBSD). But we're a minority and you know it.

**Comment by rhaberkorn** [comment]
> Sure does (although I have moved on to OpenBSD).

It must be the step before finally moving on to plan9 or resolving into a being of pure energy.
And we should really have these conversations in the (yet to be created) chatroom.

**Comment by dertuxmalwieder** [comment]
I actually use Plan9port a lot. When I finally figure out how to use venti, 9front will be my backup server. Am I enlightened enough?

**Comment by rhaberkorn** [comment]
> I actually use Plan9port a lot. When I finally figure out how to use venti, 9front will be my backup server. Am I enlightened enough?

As long as you don't drop SciTECO in favor of Sam or Acme. But you no longer need since v2.2.0 actually adds [structural patterns](https://github.com/rhaberkorn/sciteco/wiki/Useful-Macros#structural-patterns-apply-operations-to-part-of-buffer). Thanks @aksr for inspiring that!

**Comment by dertuxmalwieder** [comment]
Amazing! So, SciTECO can replace sam. Acme, on the other hand... ;-)

**Comment by rhaberkorn** [comment]
Very important and totally off-topic!!!
We can now syntax highlight SciTECO code itself.
![screenshot-1734041057](https://github.com/user-attachments/assets/d4a4f2fd-4e4a-4645-9f42-213bae082bd4)

**Comment by dertuxmalwieder** [comment]
That's awesome! It makes TECO code so much easier to read! (?) ;-)

**Comment by rhaberkorn** [comment]
> That's awesome! It makes TECO code so much easier to read! (?) ;-)

I think it does indeed help, especially in a language like TECO without lexical rules and where every character is overloaded many times. For instance it reliably shows you whether an Escape is a) escaped in a string argument, b) a string terminator or c) a regular command.
Similarly you immediately see the difference between `"~` and `X~` - in the first case it is a kind of predicate and in the other case a special Q-Register.
You immediately see mistakes like missing Escapes or `!`.
It even highlights syntactic errors.
