### ISSUE TITLE
New Binary Release?

### ISSUE THREAD

**Issue by Gavin-Holt** [rhaberkorn/sciteco#6]
Hi

WARNING: Useless windows user who can't compile code!

I tried to use the lua.tes from the master branch - with the released binary 0.6.4 and now sciteco won't launch:
```
Info: Added new unnamed file to ring.o.exe P:\MyPrograms\EDITORS\LEdit\LEdit.lua
Info: Added file "P:\MyPrograms\EDITORS\LEdit\LEdit.lua" to ring
Error: Unsupported command <^E>
Info: #0 in Q-Register "lexer.test.lua" at 72 (3:12)
Info: #1 in Q-Register "lexer.auto" at 543 (20:24)
Info: #2 in Q-Register "ED" at 107 (5:17)
Info: #3 in "ADD" hook execution
Info: #4 in file "P:\MyPrograms\EDITORS\Addins\teco\.teco_ini" at 1341 (57:25)
```
Removing the offending lua.tes file allows the editor to run. Is it possible to release the full range of lexers with the current binary release - or is it possible to make an up to date binary release for the non-compiling windows users? 

Kind Regards

Gavin

**Comment by Gavin-Holt** [comment]
Hallo

WARNUNG: Nutzloser Windows-Benutzer, der keinen Code kompilieren kann!

I tried to use the lua.tes from the master branch - with the released binary 0.6.4 and now sciteco won't launch:
Info: Added new unnamed file to ring.o.exe P:\MyPrograms\EDITORS\LEdit\LEdit.lua
Info: Added file "P:\MyPrograms\EDITORS\LEdit\LEdit.lua" to ring
Error: Unsupported command <^E>
Info: #0 in Q-Register "lexer.test.lua" at 72 (3:12)
Info: #1 in Q-Register "lexer.auto" at 543 (20:24)
Info: #2 in Q-Register "ED" at 107 (5:17)
Info: #3 in "ADD" hook execution
Info: #4 in file "P:\MyPrograms\EDITORS\Addins\teco\.teco_ini" at 1341 (57:25)


Durch das Entfernen der anstößigen Datei lua.tes kann der Editor ausgeführt werden. Ist es möglich, das gesamte Lexer-Spektrum mit der aktuellen Binärversion freizugeben - oder ist es möglich, eine aktuelle Binärversion für nicht kompilierte Windows-Benutzer zu erstellen?


Mit freundlichen Grüßen

Gavin

**Comment by rhaberkorn** [comment]
Hello Gavin!

Sorry for my long silence. I had other hobbies, so I practically paused a few years working on SciTECO. Then I decided I had to rewrite everything from C++ to C which I only recently finished.

There will soon be nightly Windows builds (at least with plain PDCurses console support), so you will never have to wait for my rare releases again! I am planning an official release soon as well and hope to release more often once this is simplified using Github workflows.
This is a cross-platform project and there is no maintainer for any of the supported platforms, so I have to do all packaging and testing on my own which is very time consuming.

For the time being, you can find a recent 32-bit Windows build (corresponding to ae913ab6275ff746439a2d99f8a1550ec2e511ff) attached. I have only tested it using Wine on Linux, so please let me know how it runs. This build may be slower than usually since it is without optimizations. I hope to get rid of some of the DLLs for the next release as well.

Download here: [sciteco-2.0.0-win32.zip](https://github.com/rhaberkorn/sciteco/files/6602833/sciteco-2.0.0-win32.zip)

**Comment by Gavin-Holt** [comment]
Hi

Many thanks, this new binary runs on my Windows 10 box. I can now use the lua.tes highlighter. I must admit I am not an expert TECO user, but everything I have learnt (and can remember!) seems to work.

I find TECO  interesting as an alternative approach to modal editing "use visible/editable macros" rather than repurposing all keys to invisible actions (VIM). TECO is hard because it's very difficult to read.

Your project combines terminal based modal editing with the power of Scintilla - neat and powerful.

If I had the skills I would substitute Lua scripting as an alternative to TECO commands. I have tried some Lua functions in other Scintilla editors ([SciTE](https://github.com/Gavin-Holt/SciTEwithStrips/blob/f1d02a134d8e450d2ad0811fb28bfa4188dd8bba/mod/SciTEStripped.lua#L170), Textadept). 

The nice thing about Lua string functions is the ability to pipe from one to the next, this allows the composition of [complex macros](http://lua-users.org/lists/lua-l/2020-02/msg00127.html) - much like TECO commands. 

I realize this is not part of your project, just my half formed ideas.

Kind Regards Gavin Holt

**Comment by rhaberkorn** [comment]
Hello Gavin,

I'm a big fan of Lua as well. But in the realm of SciTECO, it does not make much sense to introduce another scripting language when SciTECO itself is a scripting language. You can however extend SciTECO with any external command using the `EC` and `EG` commands. They allow you to pipe buffer contents into/through any external process. For instance on UNIX, you could write `10ECsort$` to sort the next 10 lines. These commands could be used to outsource text processing into Lua if you so wish (`1EClua -e "io.read():gsub(...`, you get the point).

There are also [Nightly Builds](https://nightly.link/rhaberkorn/sciteco/workflows/nightly/master) for Windows now, but you will have to wait until tomorrow for something to pop up there.
These are Curses builds running in GUI windows. GTK+ builds (real GUI) are work in progress.

**Warning:** I'm having problems with `EC` on Windows and I cannot debug them properly. I will have to set up a real Windows system before I can polish the Windows builds.

If you try any of the Windows builds, could you please answer the following questions:

* Does `EC` work as advertised?
* When hitting the "memory limit" - try typing `50*1000*1000,2EJ<%a>` - can you actually recover (rub out the loop only) and do something else or is the editor just stuck and is hitting the "memory limit" whatever you do? (If you rub out everything, you should be fine sind the EJ command is decreasing the memory limit.)
* Can you enable function key support? You will have to edit .teco_ini (`EB.teco_ini`), find the line `! EM^EQ[$SCITECOPATH]/fnkeys.tes$ !`, remove the exclamation marks (comments), save (`EW$`) and restart SciTECO. Afterwards, you should be able to navigate with cursor keys.

Best regards,
Robin
